"""Quality gate for a bone mesh arriving from outside this repo.

``inputs/bone.stl`` is generated by ``inputs/make_bone.py``, so it is watertight,
single-component, in millimetres and a few thousand triangles by construction. A
real CT-derived mesh is none of those things by construction: segmentation leaves
islands of speckle, marching cubes emits hundreds of thousands of triangles, and
whether the file is in millimetres depends on which tool wrote it.

Every one of those failures is silent downstream. A stray island shifts the mesh
bounds and moves every ray launch point; a metres-scale mesh passes every
threshold trivially because a 1.5 mm gap limit against a 0.4 mm-long femur is
meaningless. So the gate runs before a real case is accepted, and it reports in
the same ``Report``/``Check`` shape as the validators -- one report format for
the whole project.

The gate is advisory about repairs it can make (islands, holes, triangle count)
and hard about the ones it cannot (empty, unreadable, wrong scale).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from .contracts import FAIL, PASS, Check, Report

# Expected largest dimension of a whole bone, in mm. Used only to catch a mesh
# written in metres or centimetres -- these are sanity bounds, not morphometry.
BONE_EXTENT_MM = {
    "femur": (250.0, 600.0),
    "tibia": (250.0, 520.0),
    "fibula": (250.0, 500.0),
    "humerus": (200.0, 450.0),
    "radius": (150.0, 350.0),
    "ulna": (150.0, 350.0),
}
_GENERIC_EXTENT_MM = (20.0, 1200.0)

# Above this, ray casting and containment queries dominate the validator runtime.
# A decimated femur is still far finer than the gap thresholds being measured.
MAX_FACES = 200_000

# An island smaller than this fraction of the largest component is segmentation
# speckle, not anatomy.
ISLAND_FRACTION = 0.05

UNIT_SCALE_MM = {"mm": 1.0, "cm": 10.0, "m": 1000.0}


@dataclass
class MeshGateResult:
    """What the gate decided, plus the cleaned mesh if it could produce one."""

    report: Report
    mesh: object | None = None
    repairs: list[str] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        return self.report.passed


def load_mesh(path: str | Path):
    """Load any mesh trimesh can read, as a single concatenated Trimesh."""
    import trimesh

    mesh = trimesh.load(str(path), force="mesh")
    if mesh.is_empty or len(mesh.faces) == 0:
        raise ValueError(f"mesh at {path} is empty or unreadable")
    return mesh


def _check_readable(mesh) -> Check:
    n = int(len(mesh.faces))
    return Check(
        id="mesh_non_empty",
        status=PASS if n > 0 else FAIL,
        value=float(n),
        limit=1.0,
        unit="faces",
        message=f"mesh carries {n} triangles",
    )


def longest_extent_mm(mesh) -> float:
    """Longest distance across the mesh, independent of its orientation.

    Not the bounding box: a mesh arrives in scanner coordinates, obliquely
    angled, and the axis-aligned extents of a 400 mm femur lying at 30 degrees
    are all well under 400 mm. Measuring the box would report a real femur as
    implausibly short. The convex hull gives the true span.
    """
    hull = mesh.convex_hull.vertices
    if len(hull) > 2000:  # keep the pairwise distance matrix bounded
        idx = np.linspace(0, len(hull) - 1, 2000).astype(int)
        hull = hull[idx]
    diffs = hull[:, None, :] - hull[None, :, :]
    return float(np.sqrt((diffs ** 2).sum(axis=-1)).max())


def _check_units(mesh, bone: str, unit_scale: float) -> Check:
    extent = longest_extent_mm(mesh)
    lo, hi = BONE_EXTENT_MM.get(bone, _GENERIC_EXTENT_MM)
    ok = lo <= extent <= hi

    hint = ""
    if not ok:
        for name, scale in UNIT_SCALE_MM.items():
            if lo <= extent * scale <= hi:
                hint = (
                    f" -- the extent is plausible if the file is in {name}; "
                    f"re-run with --units {name}"
                )
                break

    return Check(
        id="mesh_units_plausible",
        status=PASS if ok else FAIL,
        value=round(extent, 2),
        limit=hi,
        unit="mm",
        message=(
            f"largest dimension {extent:.0f} mm is a plausible {bone} "
            f"(expected {lo:.0f}-{hi:.0f} mm, unit scale x{unit_scale:g})"
            if ok
            else f"largest dimension is {extent:.1f} mm, outside the {lo:.0f}-{hi:.0f} mm "
                 f"expected for a {bone}. Every threshold in the case is in mm, so a "
                 f"mesh at the wrong scale passes or fails them meaninglessly{hint}"
        ),
    )


def _is_enclosed_by(inner, outer) -> bool:
    """True when ``inner`` lies wholly inside ``outer``."""
    if not outer.is_watertight:
        return False
    if not ((inner.bounds[0] >= outer.bounds[0]).all()
            and (inner.bounds[1] <= outer.bounds[1]).all()):
        return False
    try:
        return bool(outer.contains(inner.vertices[:1])[0])
    except Exception:
        return False


def _drop_internal_shells(parts, repairs: list[str]):
    """Discard components nested inside another -- they are cavities, not bones.

    Thresholding a real CT keeps the cortex and rejects the marrow, so the
    segmentation is a tube. Marching cubes surfaces a tube as *two* shells: the
    outer bone surface and the inner wall of the medullary canal. They are two
    connected components of comparable size, which reads as "two bones in the
    field of view" to a naive component count -- the fixture in
    real_cases/synthetic_ct/ fails exactly that way without this.

    The implant is designed against the outer surface, so the canal shell is
    dropped rather than treated as anatomy.
    """
    outer = []
    internal = 0
    for i, part in enumerate(parts):
        if any(_is_enclosed_by(part, other) for j, other in enumerate(parts) if i != j):
            internal += 1
        else:
            outer.append(part)

    if internal:
        repairs.append(f"dropped {internal} internal cavity shell(s), e.g. a medullary canal")
    return outer or list(parts), internal


def _check_components(mesh, repairs: list[str]):
    """Split off segmentation speckle and internal cavities, keep the bone."""
    parts = mesh.split(only_watertight=False)
    if len(parts) <= 1:
        return mesh, Check(
            id="mesh_single_component",
            status=PASS,
            value=1.0,
            limit=1.0,
            unit="count",
            message="mesh is a single connected component",
        )

    parts, internal = _drop_internal_shells(parts, repairs)
    if len(parts) == 1:
        return parts[0], Check(
            id="mesh_single_component",
            status=PASS,
            value=1.0,
            limit=1.0,
            unit="count",
            message=f"kept the outer surface; {internal} internal cavity shell(s) "
                    f"removed (a thresholded cortex surfaces as a tube, so its canal "
                    f"wall arrives as a second shell)",
        )

    # Ranked by surface area, not triangle count: a 1.5 mm speck of speckle can
    # carry more triangles than a coarsely tessellated shaft, so face count says
    # nothing about which component is the anatomy.
    sizes = np.array([float(p.area) for p in parts], dtype=float)
    order = np.argsort(sizes)[::-1]
    biggest = parts[order[0]]
    kept_fraction = sizes[order[0]] / sizes.sum()
    islands = int(len(parts) - 1)
    big_islands = int((sizes[order[1:]] > ISLAND_FRACTION * sizes[order[0]]).sum())

    if big_islands:
        # Two comparable components is not speckle -- it is a second bone in the
        # field of view, or a segmentation that split the shaft. A human has to
        # look at that, so it fails rather than silently picking the larger one.
        return mesh, Check(
            id="mesh_single_component",
            status=FAIL,
            value=float(len(parts)),
            limit=1.0,
            unit="count",
            message=f"mesh has {big_islands} component(s) comparable in size to the "
                    f"largest -- the segmentation may include a second bone or have "
                    f"split the shaft. Review the segmentation before importing",
        )

    repairs.append(f"dropped {islands} speckle island(s), kept {kept_fraction:.1%} of surface area")
    return biggest, Check(
        id="mesh_single_component",
        status=PASS,
        value=float(len(parts)),
        limit=1.0,
        unit="count",
        message=f"kept the largest of {len(parts)} components ({kept_fraction:.1%} of "
                f"surface area); {islands} speckle island(s) removed",
    )


def _check_watertight(mesh, repairs: list[str]):
    """Try to close the mesh. Containment queries are undefined on an open surface."""
    if mesh.is_watertight:
        return mesh, Check(
            id="mesh_watertight",
            status=PASS,
            value=1.0,
            limit=1.0,
            unit="bool",
            message="mesh is closed",
        )

    repaired = mesh.copy()
    repaired.remove_unreferenced_vertices()
    repaired.update_faces(repaired.nondegenerate_faces())
    repaired.fill_holes()
    repaired.fix_normals()

    if repaired.is_watertight:
        repairs.append("filled holes to close the mesh")
        return repaired, Check(
            id="mesh_watertight",
            status=PASS,
            value=1.0,
            limit=1.0,
            unit="bool",
            message="mesh was open and was repaired to watertight",
        )

    return repaired, Check(
        id="mesh_watertight",
        status=FAIL,
        value=0.0,
        limit=1.0,
        unit="bool",
        message="mesh is not watertight and hole filling did not close it. "
                "bone.contains() and the gap checks need a closed surface, so the "
                "segmentation has to be cleaned before import",
    )


def _check_face_budget(mesh, repairs: list[str], max_faces: int):
    n = int(len(mesh.faces))
    if n <= max_faces:
        return mesh, Check(
            id="mesh_face_budget",
            status=PASS,
            value=float(n),
            limit=float(max_faces),
            unit="faces",
            message="triangle count is within the ray-casting budget",
        )

    try:
        reduced = mesh.simplify_quadric_decimation(face_count=max_faces)
    except Exception as exc:
        return mesh, Check(
            id="mesh_face_budget",
            status=PASS,
            value=float(n),
            limit=float(max_faces),
            unit="faces",
            message=f"{n} triangles exceeds the {max_faces} budget and decimation is "
                    f"unavailable ({exc!r}); validation will run but slowly. "
                    f"fast-simplification is in requirements.txt -- re-run setup.sh",
        )

    repairs.append(f"decimated {n} faces to {len(reduced.faces)}")
    return reduced, Check(
        id="mesh_face_budget",
        status=PASS,
        value=float(len(reduced.faces)),
        limit=float(max_faces),
        unit="faces",
        message=f"decimated from {n} triangles to fit the ray-casting budget",
    )


def gate(
    path: str | Path,
    bone: str = "femur",
    units: str = "mm",
    max_faces: int = MAX_FACES,
) -> MeshGateResult:
    """Run every mesh check, returning the cleaned mesh when it can be salvaged."""
    repairs: list[str] = []

    try:
        mesh = load_mesh(path)
    except Exception as exc:
        return MeshGateResult(report=Report.errored("mesh_readable", str(exc)))

    scale = UNIT_SCALE_MM.get(units)
    if scale is None:
        return MeshGateResult(
            report=Report.errored(
                "mesh_units", f"unknown units {units!r}, expected one of {sorted(UNIT_SCALE_MM)}"
            )
        )
    if scale != 1.0:
        mesh = mesh.copy()
        mesh.apply_scale(scale)
        repairs.append(f"scaled from {units} to mm (x{scale:g})")

    checks = [_check_readable(mesh), _check_units(mesh, bone, scale)]

    mesh, c = _check_components(mesh, repairs)
    checks.append(c)
    mesh, c = _check_watertight(mesh, repairs)
    checks.append(c)
    mesh, c = _check_face_budget(mesh, repairs, max_faces)
    checks.append(c)

    report = Report.from_checks(
        checks,
        meta={
            "validator": "mesh_quality",
            "source": str(path),
            "repairs": repairs,
            "faces": int(len(mesh.faces)),
        },
    )
    return MeshGateResult(report=report, mesh=mesh if report.passed else None, repairs=repairs)
